//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Initiumsoft_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InitiumsoftEntities1 : DbContext
    {
        public InitiumsoftEntities1()
            : base("name=InitiumsoftEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atencion> Atencion { get; set; }
    
        public virtual ObjectResult<GetAtencionTurno_Result> GetAtencionTurno(Nullable<int> iDAtencion)
        {
            var iDAtencionParameter = iDAtencion.HasValue ?
                new ObjectParameter("IDAtencion", iDAtencion) :
                new ObjectParameter("IDAtencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAtencionTurno_Result>("GetAtencionTurno", iDAtencionParameter);
        }
    
        public virtual int UpdateAtencionTurno(Nullable<int> iDAtencion)
        {
            var iDAtencionParameter = iDAtencion.HasValue ?
                new ObjectParameter("IDAtencion", iDAtencion) :
                new ObjectParameter("IDAtencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAtencionTurno", iDAtencionParameter);
        }
    
        public virtual ObjectResult<ViewAtencionTurnoTipoOne_Result> ViewAtencionTurnoTipoOne()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewAtencionTurnoTipoOne_Result>("ViewAtencionTurnoTipoOne");
        }
    
        public virtual ObjectResult<ViewAtencionTurnoTipoTwo_Result> ViewAtencionTurnoTipoTwo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewAtencionTurnoTipoTwo_Result>("ViewAtencionTurnoTipoTwo");
        }
    
        public virtual int CreateAtencionTurno(Nullable<int> cI, string nombre, ObjectParameter iDAtencion)
        {
            var cIParameter = cI.HasValue ?
                new ObjectParameter("CI", cI) :
                new ObjectParameter("CI", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateAtencionTurno", cIParameter, nombreParameter, iDAtencion);
        }
    
        public virtual int CreateAtencionTurnoPB(Nullable<int> cI, string nombre)
        {
            var cIParameter = cI.HasValue ?
                new ObjectParameter("CI", cI) :
                new ObjectParameter("CI", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateAtencionTurnoPB", cIParameter, nombreParameter);
        }
    }
}
